# Starting Objective
### I'm going to create a logistic regression classifier. And add the normal equation in addition to gradient descent.

## Details
- Convert from gradient descent to the normal equation
- Convert prediction function by wrapping current with sigmoid function
- Convert cost function and gradient descent for logistic regression
- Regularize my input
- Use advanced optimization algorithms

In [1]:
from __future__ import division
from scipy import special as scipy

import numpy as np
import math

In [60]:
class LogisticClassifier:
    
    theta = [0, 0]
    alpha = 0.01
    epoch = 300

    # Constructor
    def __init__(self, theta_size=2, alpha=0.01, epoch=5, threshold=0.5):
        self.theta = [0] * theta_size
        self.alpha = alpha
        self.epoch = epoch
        self.threshold = threshold
    
    
    # Given input x of length of j(theta_size-1)
    # Returns m(#examples) x 1 matrix of yhat
    def predict_linear(self, x):
        x = np.insert(x, 0, 1, axis=1)
        x = np.matrix(x)
        theta = np.matrix(self.theta)
        theta = theta.T
        return np.matmul(x, theta)

    
    def sigmoid(self, x):
        for a in range(x.shape[5]):
                x.item(a) = 1 / (1 + math.item(a))
        return x
    
    
    # Given training data Xtr and Ytr
    def train(self, Xtr, Ytr):        
        Ytr = np.matrix(Ytr)
        Xtr = np.matrix(Xtr)
        Ytr = Ytr.T
        self.gradient_des(Xtr, Ytr)
        
        
    # Given predictions(Yhat) and correct labels(Yte)
    # Returns squared error
    def cost_fcn(self, Yhat, Yte):
        squared_error = (Yhat - Yte)**2
        b = 1/(Yhat.size*2)
        return b * np.sum(squared_error, 0)
    
    
    # Given training data Xtr and Ytr
    # Graphs error over iterations of gradient descent
    def gradient_des(self, Xtr, Ytr):
#         j2 = np.zeros(self.epoch)
#         i2 = np.zeros(self.epoch)
        for i in range(0, self.epoch):
            Yhat = self.predict_linear(Xtr)
#             print(Yhat)
            Yhat = self.sigmoid(Yhat)
            print(Yhat)
            Ytr = np.matrix(Ytr)
            Xtr = np.matrix(Xtr)
            
            self.theta -= self.alpha * (Yhat - Ytr) * Xtr
#             j2[i] = self.cost_fcn(Yhat.A1, Ytr.A1)  # .A1 turns matrix -> array
#             i2[i] = i
#         plt.xlabel("Iterations")
#         plt.ylabel("Error")
#         plt.plot(i2, j2)

SyntaxError: can't assign to function call (<ipython-input-60-355f69c53e01>, line 27)

In [61]:
# theta = []

X = [[10], [20], [30], [40], [50], [60], [15]]
Y = [1, 1, 1, 0, 0, 1]
Xtr = X[0:5]
Ytr = Y[0:5]
Xte = X[5:6]
Yte = Y[5:6]

model = LogisticClassifier()
model.train(Xtr, Ytr)
print(model.predict_logistic(Xte))

[[0]]
[[0]]
[[0]]
[[0]]
[[0]]


ValueError: shapes (5,1) and (5,1) not aligned: 1 (dim 1) != 5 (dim 0)

### Ok... compared to Octave this is quite impractical. I'm going to switch over to tensorflow. This sigmoid function that can't be applied to a matrix in a vectorized fashion is lame. 

### Going to expand it to another repo, then come back here.

### Ok, just read the TensorFlow documentation. Let's try this again

In [1]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import tensorflow as tf

In [149]:
class LinearClassifier:
    
    weights = tf.Variable(tf.random_uniform([1,2]), 
                          tf.float32)
    
    learning_rate = tf.random_uniform(maxval=0.01, 
                                      minval=0.0001,
                                      shape=[0],
                                      dtype=tf.float32)
    
    epoch = tf.random_uniform(maxval=10, 
                              minval=300, 
                              shape=[0],
                              dtype=tf.int32)

    # Initalizes parameters
    def init(self, new_weights, new_alpha, new_epoch):
        self.theta = new_weights
        self.alpha = new_alpha
        self.epoch = new_epoch    
    
    # Given Xhat (Examples x Features)
    # Where Xhat has a rank of 2
    # Returns Yhat (Labels x 1)
    def predict(self, Xhat):
        ones = tf.ones([tf.shape(Xhat)[0], 1], tf.float32)
        x = tf.concat([ones, Xhat], 1)
        x = tf.matmul(x, tf.transpose(self.weights))
        return x
    
#     def sigmoid(self, x):
#         for a in range(x.shape[5]):
#                 x.item(a) = 1 / (1 + math.item(a))
#         return x
    
    
#     # Given training data Xtr and Ytr
#     def train(self, Xtr, Ytr):        
#         Ytr = np.matrix(Ytr)
#         Xtr = np.matrix(Xtr)
#         Ytr = Ytr.T
#         self.gradient_des(Xtr, Ytr)
        
        
    # Given predictions(Yhat) and correct labels(Yte)
    # Returns squared error
    def cost_fcn(self, Yhat, Y):
        squared_error = (Yhat - Yte)**2
        b = 1/(Yhat.shape[0])
        return b * np.sum(squared_error, 0)
    
    
#     # Given training data Xtr and Ytr
#     # Graphs error over iterations of gradient descent
#     def gradient_des(self, Xtr, Ytr):
# #         j2 = np.zeros(self.epoch)
# #         i2 = np.zeros(self.epoch)
#         for i in range(0, self.epoch):
#             Yhat = self.predict_linear(Xtr)
# #             print(Yhat)
#             Yhat = self.sigmoid(Yhat)
#             print(Yhat)
#             Ytr = np.matrix(Ytr)
#             Xtr = np.matrix(Xtr)
            
#             self.theta -= self.alpha * (Yhat - Ytr) * Xtr
#             j2[i] = self.cost_fcn(Yhat.A1, Ytr.A1)  # .A1 turns matrix -> array
#             i2[i] = i
#         plt.xlabel("Iterations")
#         plt.ylabel("Error")
#         plt.plot(i2, j2)

In [168]:
# TESTING COST FUNCTION

with tf.Session() as sess:
    model = LinearClassifier()
    X = tf.Variable([[7],[11]], dtype=tf.float32)
    Y = tf.Variable([[14],[22]], dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    
    Yhat = model.predict(X)

    print("Input")
    a = X
    b = tf.Print(a, [a])
    print(sess.run(b))
    
    print("\nWeights")
    c = model.weights
    d = tf.Print(c, [c])
    print(sess.run(d))
    
    print("\nPrediction")
    e = Y
    f = tf.Print(e, [e])
    print(sess.run(f))

    print("\n1st Element Expectation")
    k = model.weights[0,0]*1 + model.weights[0,1]*X[0,0]
    p = tf.Print(k, [k])
    print("{} vs {}".format(sess.run(p), sess.run(f)[0]))

Input
[[ 7.]
 [11.]]

Weights
[[0.6075765  0.18066156]]

Prediction
[[14.]
 [22.]]

1st Element Expectation
1.8722074031829834 vs [14.]


In [169]:
# TESTING PREDICT

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    model = LinearClassifier()
    if 'Xhat' not in globals():
        Xhat = tf.get_variable("Xhat", [5,1]) # tf.float32, tf.glorot_uniform_initializer, by default
    Yhat = model.predict(Xhat)
    
    print("Input")
    a = Xhat
    b = tf.Print(a, [a])
    print(sess.run(b))
    
    print("\nWeights")
    c = model.weights
    d = tf.Print(c, [c])
    print(sess.run(d))
    
    print("\nPrediction")
    e = Yhat
    f = tf.Print(e, [e])
    print(sess.run(f))

    print("\n1st Element Expectation")
    k = model.weights[0,0]*1 + model.weights[0,1]*Xhat[0,0]
    p = tf.Print(k, [k])
    print("{} vs {}".format(sess.run(p), sess.run(f)[0]))
    
    print("\nThus PREDICT works")

Input


FailedPreconditionError: Attempting to use uninitialized value Xhat
	 [[Node: Xhat/read = Identity[T=DT_FLOAT, _class=["loc:@Xhat"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Xhat)]]

Caused by op 'Xhat/read', defined at:
  File "/anaconda3/envs/tensorflow/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/envs/tensorflow/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 486, in start
    self.io_loop.start()
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "/anaconda3/envs/tensorflow/lib/python3.6/asyncio/base_events.py", line 422, in run_forever
    self._run_once()
  File "/anaconda3/envs/tensorflow/lib/python3.6/asyncio/base_events.py", line 1432, in _run_once
    handle._run()
  File "/anaconda3/envs/tensorflow/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 117, in _handle_events
    handler_func(fileobj, events)
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2903, in run_ast_nodes
    if self.run_code(code, result):
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-113-6ae6e94ac33a>", line 7, in <module>
    Xhat = tf.get_variable("Xhat", [5,1]) #tf.float32, tf.glorot_uniform_initializer
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1297, in get_variable
    constraint=constraint)
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1093, in get_variable
    constraint=constraint)
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 439, in get_variable
    constraint=constraint)
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 408, in _true_getter
    use_resource=use_resource, constraint=constraint)
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 800, in _get_single_variable
    use_resource=use_resource)
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2157, in variable
    use_resource=use_resource)
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2147, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2130, in default_variable_creator
    constraint=constraint)
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 235, in __init__
    constraint=constraint)
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 391, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 142, in identity
    return gen_array_ops.identity(input, name=name)
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 3053, in identity
    "Identity", input=input, name=name)
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3290, in create_op
    op_def=op_def)
  File "/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value Xhat
	 [[Node: Xhat/read = Identity[T=DT_FLOAT, _class=["loc:@Xhat"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Xhat)]]


In [12]:
# TF TEST: PRINTING TENSOR
with tf.Session() as sess:
    r = tf.random_uniform([1])
    p = tf.Print(r, [r])
    print(r)
    print(sess.run(p))

Tensor("random_uniform_11:0", shape=(1,), dtype=float32)
[0.23018432]


In [148]:
# TF TEST: TENSOR OPERATIONS
with tf.Session() as sess:
    a = tf.Variable([[7],[11]], tf.int16)
    b = tf.Variable([[20],[11]], tf.int16)
    sess.run(tf.global_variables_initializer())
    
    r = (a - b)**2
    p = tf.Print(r, [r])
    print(sess.run(p))

[[169]
 [  0]]
